# Generated by Django 5.1.8 on 2025-06-27 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0008_violationsubmission_created_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="violationreport",
            name="violation_observed",
            field=models.CharField(db_index=True),
        ),
        migrations.AlterField(
            model_name="violationsubmission",
            name="captured_at",
            field=models.DateTimeField(db_index=True),
        ),
    ]
