# Generated by Django 5.1.14 on 2025-12-10 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0009_alter_violationreport_violation_observed_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="violationreport",
            name="service_id",
            field=models.CharField(blank=True, null=True),
        ),
    ]
