# Generated by Django 5.1.15 on 2026-01-18 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("lazer", "0018_lazersession"),
    ]

    operations = [
        migrations.CreateModel(
            name="Banner",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("content", models.TextField(help_text="Markdown content (supports links)")),
                (
                    "color",
                    models.CharField(
                        choices=[("pink", "Pink"), ("green", "Green")],
                        default="green",
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Banner",
                "verbose_name_plural": "Banners",
            },
        ),
    ]
