# Generated by Django 5.1.8 on 2025-06-30 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0016_alter_profile_user_discordactivity"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="discordactivity",
            index=models.Index(fields=["profile", "date"], name="profiles_di_profile_1454a5_idx"),
        ),
    ]
