# Generated by Django 5.1.8 on 2025-09-06 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0017_discordactivity_profiles_di_profile_1454a5_idx"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="council_district",
        ),
    ]
