# Generated by Django 5.1.8 on 2025-09-22 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0018_remove_profile_council_district"),
    ]

    operations = [
        migrations.CreateModel(
            name="DoNotEmail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "reason",
                    models.CharField(
                        choices=[
                            ("account_deletion", "Account Deletion"),
                            ("known_opponent", "Known Opponent"),
                        ],
                        max_length=50,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name": "Do Not Email",
                "verbose_name_plural": "Do Not Email",
            },
        ),
    ]
