# Generated by Django 5.1.8 on 2025-10-06 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0019_donotemail"),
    ]

    operations = [
        migrations.AddField(
            model_name="shirtorder",
            name="product_type",
            field=models.IntegerField(choices=[(0, "T-Shirt"), (1, "Sweatshirt")], default=0),
        ),
        migrations.AlterField(
            model_name="shirtorder",
            name="fit",
            field=models.IntegerField(
                choices=[
                    (2, 'Unisex Classic Fit - "Next Level - Cotton T-Shirt - 3600"'),
                    (3, "Women's Relaxed Fit - \"Next Level - Women's Ideal Crop Top - 1580\""),
                    (4, 'Unisex Classic Fit - "Gildan G180 - Heavy Blend Crewneck Sweatshirt"'),
                ]
            ),
        ),
    ]
