# Generated by Django 5.1.15 on 2026-01-14 15:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles", "0021_alter_profile_newsletter_opt_in"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="pronouns",
            field=models.CharField(max_length=64, null=True, verbose_name="Pronouns"),
        ),
    ]
