# Generated by Django 5.1.8 on 2025-09-08 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("events", "0007_remove_eventsignin_mailchimp_contact_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="scheduledevent",
            name="hidden",
            field=models.BooleanField(default=False),
        ),
    ]
