# Generated by Django 5.1.8 on 2025-09-05 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("membership", "0004_donationproduct_disclaimer_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="donation",
            name="comment",
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
