# Generated by Django 5.1.8 on 2025-10-15

from django.db import migrations, models
from django.utils.text import slugify


def populate_slugs(apps, schema_editor):
    Election = apps.get_model("elections", "Election")
    for election in Election.objects.all():
        election.slug = slugify(election.title)
        election.save()


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="election",
            name="slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.RunPython(populate_slugs, migrations.RunPython.noop),
        migrations.AlterField(
            model_name="election",
            name="slug",
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
