# Generated by Django 5.1.8 on 2025-10-15 09:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0002_election_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Nominee",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "photo",
                    models.ImageField(
                        blank=True,
                        help_text="A headshot, selfie, or even discord profile picture",
                        null=True,
                        upload_to="nominee_photos/",
                    ),
                ),
                (
                    "public_display_name",
                    models.CharField(
                        blank=True,
                        help_text=(
                            "Optional, if you go by a different name than you "
                            "provided on your profile"
                        ),
                        max_length=255,
                    ),
                ),
                (
                    "board_responsibilities_acknowledged",
                    models.BooleanField(
                        default=False,
                        help_text="I have read the PBA Board responsibilities and expectations",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "election",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominees",
                        to="elections.election",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominee_records",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("election", "user")},
            },
        ),
        migrations.CreateModel(
            name="Nomination",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "nomination_statement",
                    models.TextField(
                        blank=True, default="", help_text="Why are you nominating this person?"
                    ),
                ),
                ("draft", models.BooleanField(default=False)),
                (
                    "acceptance_status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("acceptance_date", models.DateTimeField(blank=True, null=True)),
                (
                    "acceptance_note",
                    models.TextField(
                        blank=True,
                        help_text="Optional note from nominee about their decision",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "nominator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations_given",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "nominee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nominations",
                        to="elections.nominee",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
                "unique_together": {("nominee", "nominator")},
            },
        ),
    ]
