# Generated by Django 5.1.8 on 2025-10-15 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("elections", "0003_nominee_nomination"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nominee",
            name="board_responsibilities_acknowledged",
            field=models.BooleanField(
                default=False,
                help_text=(
                    "I have read the <a href='https://docs.google.com/document/d/"
                    "1ptPY_IUtLQR6gI_yN76YwRmKGN9SsWXwol66HLl5iS0/edit?tab=t.0' "
                    "target='_blank'>PBA Board responsibilities and expectations</a>"
                ),
            ),
        ),
    ]
