# Generated by Django 5.1.15 on 2026-01-18 22:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("campaigns", "0028_campaign_districts_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="petition",
            name="post_sign_email_body",
            field=models.TextField(
                blank=True,
                help_text=(
                    "Body of the post-sign email. Supports markdown and Django template syntax. "
                    "Available context: first_name, last_name, email, petition, campaign."
                ),
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="petition",
            name="post_sign_email_enabled",
            field=models.BooleanField(
                default=False, help_text="Send an email to the signer after they sign the petition"
            ),
        ),
        migrations.AddField(
            model_name="petition",
            name="post_sign_email_subject",
            field=models.CharField(
                blank=True,
                help_text="Subject line for the post-sign email. Supports Django template syntax.",
                max_length=988,
                null=True,
            ),
        ),
    ]
